AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for internal network environment

Parameters:
  ProjectName:
    Type: String
    Default: hs-internal
  CidrBlockVPC:
    Type: String
    Default: 172.16.0.0/16
  CidrBlockNLBPrivateSubnetA:
    Type: String
    Default: 172.16.0.0/24
  CidrBlockAppPrivateSubnetA:
    Type: String
    Default: 172.16.10.0/24
  CidrBlockAppPrivateSubnetC:
    Type: String
    Default: 172.16.11.0/24
  CidrBlockDbPrivateSubnetA:
    Type: String
    Default: 172.16.20.0/24
  CidrBlockDbPrivateSubnetC:
    Type: String
    Default: 172.16.21.0/24

Resources:
  # VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-vpc.yml
      Parameters:
        ProjectName: !Ref ProjectName
        CidrBlockVPC: !Ref CidrBlockVPC
        CidrBlockNLBPrivateSubnetA: !Ref CidrBlockNLBPrivateSubnetA
        CidrBlockAppPrivateSubnetA: !Ref CidrBlockAppPrivateSubnetA
        CidrBlockAppPrivateSubnetC: !Ref CidrBlockAppPrivateSubnetC
        CidrBlockDbPrivateSubnetA: !Ref CidrBlockDbPrivateSubnetA
        CidrBlockDbPrivateSubnetC: !Ref CidrBlockDbPrivateSubnetC
  # セキュリティグループ
  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-sg.yml
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPC.Outputs.VpcId
        CidrBlockVPC: !Ref CidrBlockVPC
  # VPCエンドポイント
  Endpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-endpoint.yml
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPC.Outputs.VpcId
        AppPrivateSubnetA: !GetAtt VPC.Outputs.AppPrivateSubnetA
        VpcEndpointSecurityGroup: !GetAtt SecurityGroup.Outputs.VpcEndpointSecurityGroup
  # 踏み台サーバー
  BastionEC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-bastion.yml
      Parameters:
        ProjectName: !Ref ProjectName
        AppPrivateSubnetA: !GetAtt VPC.Outputs.AppPrivateSubnetA
        AppSecurityGroup: !GetAtt SecurityGroup.Outputs.AppSecurityGroup
  # Cognito
  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-cognito.yml
      Parameters:
        ProjectName: !Ref ProjectName
  # S3
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-s3.yml
      Parameters:
        ProjectName: !Ref ProjectName
  # ELB
  ELB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-elb.yml
      Parameters:
        ProjectName: !Ref ProjectName
        NLBPrivateSubnetA: !GetAtt VPC.Outputs.NLBPrivateSubnetA
        AppPrivateSubnetA: !GetAtt VPC.Outputs.AppPrivateSubnetA
        AppPrivateSubnetC: !GetAtt VPC.Outputs.AppPrivateSubnetC
        ALBSecurityGroup: !GetAtt SecurityGroup.Outputs.ALBSecurityGroup
        VpcId: !GetAtt VPC.Outputs.VpcId
        ALBLogBucket: !GetAtt S3.Outputs.ALBLogBucket
