AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for internal network environment

Parameters:
  ProjectName:
    Type: String
  NLBPrivateSubnetA:
    Type: String
  AppPrivateSubnetA:
    Type: String
  AppPrivateSubnetC:
    Type: String
  ALBSecurityGroup:
    Type: String
  VpcId:
    Type: String
  ALBLogBucket:
    Type: String

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: !Join [ "-", [ !Ref ProjectName, "alb" ] ]
      Scheme: internal
      Subnets:
        - !Ref AppPrivateSubnetA
        - !Ref AppPrivateSubnetC
      SecurityGroups:
        - !Ref ALBSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !Ref ALBLogBucket
  ALBFrontTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join [ "-", [ !Ref ProjectName, "front", "alb", "tg" ] ]
      HealthCheckEnabled: true
      Protocol: HTTP
      Port: 80
      TargetType: ip
      VpcId: !Ref VpcId
  ALBProxyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join [ "-", [ !Ref ProjectName, "proxy", "alb", "tg" ] ]
      HealthCheckEnabled: true
      Protocol: HTTP
      Port: 80
      TargetType: ip
      VpcId: !Ref VpcId
  # NLB
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Name: !Join [ "-", [ !Ref ProjectName, "nlb" ] ]
      Scheme: internal
      IpAddressType: ipv4
      Subnets:
        - !Ref NLBPrivateSubnetA
  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join [ "-", [ !Ref ProjectName, "nlb", "tg" ] ]
      HealthCheckEnabled: true
      Protocol: TCP
      Port: 80
      TargetType: alb
      Targets:
        - Id: !Ref ALB
          Port: 80
      VpcId: !Ref VpcId
  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref NLBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
